### ISSUE TITLE
author management

### ISSUE THREAD

**Issue by jamiroconca** [nk-o/visual-portfolio#100]
hi,
it seems like portfolio's author management isn't available and since it's a standard post type feature it would be nice having it

**Comment by nk-o** [comment]
Do you mean additional user role, something like this one? https://github.com/nk-o/docspress/blob/31aa4d8be67ae32a21895d7115ba4089b78d676d/src/docspress.php#L167-L197

**Comment by jamiroconca** [comment]
mmh, no. I mean the possibility assign a different author to a post type, standard mode.
