### ISSUE TITLE
Custom Query filters does not work for category_name and tag

### ISSUE THREAD

**Issue by tursoft** [nk-o/visual-portfolio#109]
Hi,

I have just tries to filter portfolio items by using category_name and/or tag filters but it does not work. is thare any trick to make it work?

**post_type=portfolio&category_name=projects**

Best regards.

**Comment by nk-o** [comment]
Hi.

Answer with a solution here - https://wordpress.org/support/topic/custom-query-filters-does-not-work-for-category_name-and-tag/
