### ISSUE TITLE
Multiple filter box extension

### ISSUE THREAD

**Issue by suryadarmana** [nk-o/visual-portfolio#110]
Hey is it possible to extends this plugin to filter multiple taxonomies via multiple select dropdown? I tried to add multiple select dropdown in custom layout but the filter seems not working, am i doing it wrong? Thanks @nk-o
![Screenshot_2019-05-06 Projects](https://user-images.githubusercontent.com/10684476/57232293-7e454000-7046-11e9-9000-8ba76b47f1c5.png)

**Comment by suryadarmana** [comment]
Hi, thank you for the confirmation, can't wait to see that features in the future! You're plugin is super awesome and really helpful

**Comment by nk-o** [comment]
Hey.

Added filter for query arguments. If you are familiar with WordPress WP_Query, it will be easy for you, to add additional filters.

New filter `vpf_extend_query_args` will be available in coming plugin update. Commit https://github.com/nk-o/visual-portfolio/commit/f14b7f509dfdd478b5bc35424ed45a547d3056da

p.s. Multiple selects you can add in templates `items-list/filter/`
p.s.2. If you will need some additional filters, don't be afraid to make PRs https://github.com/nk-o/visual-portfolio/pulls

**Comment by suryadarmana** [comment]
Woah, that's awesome! gonna check it soon, thank you
