### ISSUE TITLE
Tiles flicker on load more

### ISSUE THREAD

**Issue by nk-o** [nk-o/visual-portfolio#114]
Related topic: https://wordpress.org/support/topic/tiles-flicker-on-load-more/

[visualportfolioflickering.zip](https://github.com/nk-o/visual-portfolio/files/3210712/visualportfolioflickering.zip)

**Comment by kameha** [comment]
I have the same problem. Appearing animation is probably to fast and as images come from the side (I don't know why) it makes the tiles flicker.

**Comment by nk-o** [comment]
I'm not sure, but probably this is already fixed in the latest version? I don't see this flickering on our demo https://visualportfolio.co/tiles-custom-color/
