### ISSUE TITLE
Updated to Version 1.12.0 - Video Popup Gallery only works for Youtube URLS

### ISSUE THREAD

**Issue by ChrisCampDesigns** [nk-o/visual-portfolio#116]
Upon Updating Visual Portfolio to Version 1.12.0
• changed video oembed loading method
no more php oembed since it may be too heavy to load pages (used JS instead)
• no more video thumbnail loading if no featured image specified in post

Since the last update, the portfolio plugin no longer shows Vimeo, MP4, or Mediazilla urls in the popup gallery. Youtube works fine, but the people I work with are using Mediazilla and MP4 file locally hosted. Any suggestions as to how I should fix this issue?

**Comment by nk-o** [comment]
Fixed in https://github.com/nk-o/visual-portfolio/commit/12b9591f977b37b0e0318ae86e8c5d113e5c4ed1

The plugin will be updated soon.
