### ISSUE TITLE
Visual Portfolio does not work

### ISSUE THREAD

**Issue by visualportfoliodoesnotwork** [nk-o/visual-portfolio#119]
Hi!

As soon as I activate the Visual Portfolio plugin (which is installed automatically with the Leedo theme) I get this error on all of my pages:

Warning: session_start(): open(D:appdataPHPPHP-7.3sessionssess_6059f2e0362997cff237479321932f5c, O_RDWR) failed: Permission denied (13) in D:appdataIISvhostsstudiomarco.nlhttpdocswp-contentpluginsvisual-portfolioclassesclass-get-portfolio.php on line 25

Warning: session_start(): Failed to read session data: files (path: D:appdataPHPPHP-7.3sessions) in D:appdataIISvhostsstudiomarco.nlhttpdocswp-contentpluginsvisual-portfolioclassesclass-get-portfolio.php on line 25

How do I fix this? Leedo said to contact you.

Thanks!  Kind regards,

Nena

**Comment by nk-o** [comment]
Hi Nena.

Your site is having issues writing data to the session (Permission Denied). This is probably something to ask your host about.

Regards, nK.
