### ISSUE TITLE
Carousel thumbnails don't reload after filtering

### ISSUE THREAD

**Issue by nk-o** [nk-o/visual-portfolio#123]
Related topic: https://wordpress.org/support/topic/show-only-relevant-thumbnails/

**Comment by Zunichi** [comment]
Thanks Nikita. Are you the only one working out all the bugs? I'm not big on PHP but if you can point me in the right direction, perhaps I can take a look at it.

**Comment by nk-o** [comment]
Yes, almost all our free plugins I develop and fix by myself.

I think the problem in these lines:
https://github.com/nk-o/visual-portfolio/blob/f61de2360d18539349c48b8e1ac132f9954ccc18/src/assets/js/script.js#L2115-L2125

We update slider images but does nothing for thumbnails.

**Comment by Zunichi** [comment]
Got a chance to try fixing this bug yet? I tried looking at it but not having any luck even making sense of it.

**Comment by Zunichi** [comment]
Can we somehow disable ajax for now until this gets fixed? The thumbnails seem to work if the page reloads to the filter link.

**Comment by nk-o** [comment]
@Zunichi please, wait for the plugin update, it will be in 1-2 days.

**Comment by Zunichi** [comment]
Thank you! Glad to hear.

**Comment by Zunichi** [comment]
Thanks. I downloaded the files from here but its giving out errors. Should I wait till it gets updated in the Wordpress repository?
