### ISSUE TITLE
 filters dont work

### ISSUE THREAD

**Issue by lefor** [nk-o/visual-portfolio#125]
hi i installed this plugin and found it really useful but there is a problem with that the filters dont work what should i do? help me please
https://kharraziyas.ir/%D9%85%DB%8C%D9%86%DB%8C-%D8%B4%D8%A7%D9%BE/

**Comment by nk-o** [comment]
See solution in this FAQ section https://visualportfolio.co/documentation/faq/#accordion-why-filtering-is-not-filter-items
