### ISSUE TITLE
Error doesn't show projects

### ISSUE THREAD

**Issue by joanpaae** [nk-o/visual-portfolio#130]
When I selected "Project" in "Data Source", it doen't show my projects.

This happened after the last update.
Please help me.
Thanks

<img width="1243" alt="Captura de pantalla 2020-03-12 17 54 36" src="https://user-images.githubusercontent.com/39574866/76565997-9cf83c80-648a-11ea-9495-05ac1d53ad70.png">
<img width="1262" alt="Captura de pantalla 2020-03-12 17 53 41" src="https://user-images.githubusercontent.com/39574866/76566006-a08bc380-648a-11ea-832d-1d1bf89c18b8.png">

**Comment by nk-o** [comment]
Hey. There is a bug with Taxonomies Relation option = AND. Try to change it to OR and let me know if it works.

**Comment by joanpaae** [comment]
Works correctly.  Thanks.  The plugins is great.
