### ISSUE TITLE
Filter dropdown list of categories and tags

### ISSUE THREAD

**Issue by edsonrodsilva** [nk-o/visual-portfolio#132]
Hello,
First I would like to thank you for the fantastic plugin this is really the best portfolio plugins I know.
![dropdown_visual_portfolio](https://user-images.githubusercontent.com/2845966/78670419-192c4700-78b4-11ea-952f-74506de036b6.png)

I would like to have two filter dropdown, one with my categories and the other with my tags.

Like this: https://drive.google.com/file/d/1BcYdXNLNp6lPgTe8ieCRDJcNcJgnLv4U/view

I am studying how to do it but still without success.
Can anybody help me.

Thanks.

**Comment by nk-o** [comment]
Hey.

There are plans to add an advanced filter in the PRO plugin version. It is still in development, so, no solution for now.
