### ISSUE TITLE
Is there a way to make the title show by default? If not, that would be great to add! 

### ISSUE THREAD

**Issue by swhitlow** [nk-o/visual-portfolio#137]
Awesome plugin!! This has been the best one I have found by far! Is there a way to make the title visible by default? I am trying to replicate something similar to this: (scroll down to the first image gallery of the cities)

https://cousins.com/

I know I would need to edit the meta.php or image.php files in the templates folders but just not sure exactly where to make it so the title is visible by Default. Thanks!

**Comment by nk-o** [comment]
Hey.

I see you already marked this issue on WordPress forums as resolved.

The option to change the fade background and text colors before hovering will be added in the future updates.

Regards, nK.
