### ISSUE TITLE
Is it possible to create portfolio items with JSON API?

### ISSUE THREAD

**Issue by peterdk** [nk-o/visual-portfolio#140]
Really like this visual-portfolio. I am busy setting up a site for a visual artist, and was wondering if it's possible to create portfolio items programmatically. For example using the Wordpress API?  I seem to be able to get /portfolio and then get all the items. But am a bit left wondering if it's also possible to create. Am new to Wordpress, so the API part is something I am still figuring out.

**Comment by peterdk** [comment]
Well, to answer my own question: yes!
Ruby:
```
#Upload image as media:
url = "example.com/wp-json/wp/v2/media"
response = RestClient.post url , { :file => File.new(painting.file), :date => painting.date.to_s, :title => painting.title, 
:caption => painting.caption, :description => painting.caption}, 
      {:content_type => "image/jpg", :content_disposition => "form-data;filename ='#{painting.file}'"}
      return JSON.parse(response)["id"]    

#add portfolio item for that image
url = "example.com/wp-json/wp/v2/portfolio"
RestClient.post url, {:title => painting.title, :date => painting.date.to_s, :excerpt => painting.excerpt, 
:featured_media => media_id, :portfolio_category => categories ,:status => "publish"}
```

**Comment by nk-o** [comment]
Yep, it is possible with default WordPress API, as you know now :)
