### ISSUE TITLE
Having trouble customising the filter

### ISSUE THREAD

**Issue by vanessaeggs** [nk-o/visual-portfolio#141]
Hi, 
I think I may be adding the code to the wrong file. I have read the documentation but nothing I change is actually taking effect. 
Which file should I be editing to add a custom filter?
In a perfect scenario I would like to have 3. I have been able to duplicate the dropdown > filter.php to have 2 dropdown filters, but I dont know how to change the second filter from categories to tags. No where in all the forums I've read or documentation does anything say which files should be edited.

**Comment by nk-o** [comment]
Hi.  
  
You can override plugin templates in your theme https://visualportfolio.co/documentation/developers/changing-default-templates-and-styles/  
  
If you want to add your own filters, you will need to add it by yourself, as we don't provide such settings. Our filter generates automatically based on item categories.

https://github.com/nk-o/visual-portfolio/blob/c261814f75d86cdcf26fcdd10106ff85b87d4e69/src/classes/class-get-portfolio.php#L597-L635
