### ISSUE TITLE
Image's Not displaying on Hauwei p30 Lite

### ISSUE THREAD

**Issue by Vliesie** [nk-o/visual-portfolio#142]
Hi

Image's for my Gallery and Sliders and displaying on my mobile device but do display on my Browsers. When I test In Responsive Tool's 

But on my phone it just refuses to load the image's Weather on Desktop Site or Mobile Site.

Also checked settings no download limit on image's

2nd Attempts were trying to reduce all image sizes to less then 500kb 
Result remains the same
![Screenshot_20200723_124936_com android chrome](https://user-images.githubusercontent.com/43061831/88279214-f64b6480-cce3-11ea-8970-74cb4ce7764f.jpg)
![Screenshot_20200723_124946_com android chrome](https://user-images.githubusercontent.com/43061831/88279228-fb101880-cce3-11ea-9a55-82af910aac81.jpg)
![Screenshot_20200723_124950_com android chrome](https://user-images.githubusercontent.com/43061831/88279232-fba8af00-cce3-11ea-98d9-b0eccf938d37.jpg)

**Comment by Vliesie** [comment]
Also Tested on 2 Iphone/s 8/6 and a Haweu p10 Lite

**Comment by nk-o** [comment]
Can you provide your site URL?

**Comment by kalpeshmordiya** [comment]
Same here i have taken latest version and try to configure but not working can please help me

**Comment by nk-o** [comment]
The issue closed, as no answer received.
