### ISSUE TITLE
Updating plugin to 2.8.0 broke all carousels

### ISSUE THREAD

**Issue by Youdaman** [nk-o/visual-portfolio#146]
Hi, just a heads up, not sure what the actual cause is, but I had multiple carousels all working on my site and after updating the plugin to the latest version 2.8.0 they're all broken.

By "broken" I mean that their preview is not displaying in the editor correctly, either grey boxes where the images should be, or the dimensions of existing carousels are squased flat instead of showing slides/images at the proper height.

I'll try to work out what the issue is but I guess the only way to reproduce at your end is to create an image slideshow with the previous version and then update the plugin to see if it breaks. Might need for me to also add settings for the carousel if that doesn't break things, perhaps it's one of the settings like height being Auto for example.

**Comment by Youdaman** [comment]
Reverting to 2.7.1 fixes the issues. Not sure what the cause was/is but can share carousel settings if you cannot reproduce.

**Comment by nk-o** [comment]
Hey.  
  
Have you checked it in the 2.8.1 plugin update?

**Comment by Youdaman** [comment]
Yeah just tried it, upgrading from 2.7.1 to 2.8.1, same problem -- I have a few carousels/grids on one page and they all turn into grey boxes (no preview) in the editor. Only thing I can suggest for bug repro is install 2.7.1, create some carousels, update to 2.8.x and see what happens at your end.

**Comment by nk-o** [comment]
There was a problem with block preview and WP Multisite (it will be fixed in the next plugin update). Have you used Multisite? If no, can you create a private ticket in our support system? https://nk.ticksy.com/

**Comment by Youdaman** [comment]
Yes it's Multisite. Look forward to the fix, thank you!

**Comment by nk-o** [comment]
fixed in 7c02449
