### ISSUE TITLE
Popup gallery interface bugs

### ISSUE THREAD

**Issue by devalot76** [nk-o/visual-portfolio#81]
Avada header (with "sticky" option) and scrolling to top area are still in the foreground when Popup Gallery is showed (please refer to the screenshot). Also, the image caption is cutted.

![screenshot](https://user-images.githubusercontent.com/25148076/48978007-9717f580-f0a5-11e8-8b5d-417d4164d069.jpg)

**Comment by nk-o** [comment]
Hi.

To fix Avada navigation overlapping, you can add custom CSS:

```css
.vp-pswp {
    z-index: 10010;
}
```

Bug with the caption position will be fixed in plugin update.
