### ISSUE TITLE
More carousel settings

### ISSUE THREAD

**Issue by nk-o** [nk-o/visual-portfolio#83]
1. Pause autoplay on mouse over
2. Free mode sticky to slides (freeModeSticky)
3. Thumbnails

**Comment by whatsnewsisyphus** [comment]
Thought I'd chime-in with an extra here:
3. Carousel/slider wrapper height:
It would be great to have a screen relative slider height option on the front end so people can use it to make full-height heroes. I just added a height:100vh to the slider wrapper but something more cross-browser might be better.

Also, thanks a million for developing this plugin. I just added some suggestions and bug fixes to the tracker.

Let me know what a good donation address is and I'll drop you some change if I get to use it for a paying client.

**Comment by nk-o** [comment]
Currently, we have slide height, so maybe just need to extend this option to make possible to add `vh` unit.

![image](https://user-images.githubusercontent.com/14810891/50592900-24b9e280-0ea7-11e9-937b-ebae0aa14615.png)

`vh` unit works in IE9. It's pretty ok :)

We make this plugin to use in our premium themes, so we don't need donation for now. Also in the future, we have plans for PRO addon for this plugin.

**Comment by whatsnewsisyphus** [comment]
What is the dynamic a %of? It's not screen height, it ends up being much
larger than the screen with 100%. That's why I had to set it with CSS. This
is using it as a Gutenberg block.

**Comment by whatsnewsisyphus** [comment]
Still haven't figured out what the dynamic % refers to, it's not screenheight.
Anyhow, may I add a request for thumbnails? It's available on swiper demos
https://idangero.us/swiper/demos/

**Comment by whatsnewsisyphus** [comment]
Ok, so heigh by percentage is just percentage of the width where 100% is square. That is really confusing. I think maybe a better way to approach this is to separate image height and slider container height and offer an option where the images fit the height of the container and not necessarily fill it. Like here https://github.com/nolimits4web/Swiper/blob/master/demos/140-centered-auto.html

**Comment by nk-o** [comment]
Yes, `%` - is dynamic from slides width. But I told you that need to extend functionality and add here `vh` units or a custom one. In other words, this is not added, this `will` be added in the future updates.
