### ISSUE TITLE
Add data-srcset to a or parse img tag for Fancybox responsive

### ISSUE THREAD

**Issue by whatsnewsisyphus** [nk-o/visual-portfolio#86]
Realized you are not using fancy box. Srcset will  help with swapping light boxes in the future if need be but photoswipe never implemented support, you could potentially parse filenames for it if people choose it. 

The script already works with data-srcset for the thumbnails in the grid but does not pass them on to fancybox. Fancybox has already built this in with lazy loading, you just have to pass data-srcset in the parent a element. I was going to add it and do a pull request but things get a bit confusing with the $args being passed around so I thought it better if you do it.

[official codepen](https://codepen.io/fancyapps/pen/LJwvzY?editors=1000)
[my codepen combining both srcsets](https://codepen.io/whatsnewsisyphus/pen/JwKrMR)

**Comment by whatsnewsisyphus** [comment]
I dug through a bit and realized that you use your own data for popups with data-vp-popup-*-img-size. That works so this can probably be on the backburner. Srcset might be easier on the js front being built into fancybox, help reduce extras.

**Comment by nk-o** [comment]
I'll check this when will work on Fancybox integration https://github.com/nk-o/visual-portfolio/issues/36

**Comment by nk-o** [comment]
added Fancybox https://github.com/nk-o/visual-portfolio/commit/d69dd86c5b2652b6be8a931039824f486c11825d
