### ISSUE TITLE
Better handling for grid img sizes attribute

### ISSUE THREAD

**Issue by whatsnewsisyphus** [nk-o/visual-portfolio#87]
Currently the script generates the sizes attribute on resize using js and uses the vpf class prefixes before js is loaded which can cause some load order issues. Resize and load calculations also add and affect render speed and pagespeed numbers. Luckily, the fix is pretty easy.

A better and easier way of doing it is using media queries and basic math so that it outputs the following for each breakpoint down to 100vw for the mobile where the grid drops to one image per column.

In simplified php:
for each breakpoints as breakpoint
'(max-width:' . $breakpoint[width] . ') ' . math(100/$breakpoint[columncount]) . 'vw'

[see result](https://codepen.io/whatsnewsisyphus/pen/JwKrMR) in codepen

**Comment by nk-o** [comment]
Sizes attribute generates by https://github.com/aFarkas/lazysizes plugin. We need to calculate the actual block size instead of using static sizes. For example, this works well for Tiles layout https://wp.nkdev.info/free-visual-portfolio/tiles-custom-color/.

**Comment by whatsnewsisyphus** [comment]
Yes, what I was proposing was similar with css. Didn't realize lazysizes
was doing the calculations. I will look at the impact of lazy sizes on
redraw with a large number of image elements.

How does it all degrade without js? I tried disabling Java and nothing
loaded. I was hoping that it would work to load images still.

**Comment by nk-o** [comment]
Visual Portfolio is not working without JS. Who nowadays disable JS in their browsers?
