### ISSUE TITLE
Simpler default (without zoom transition)

### ISSUE THREAD

**Issue by whatsnewsisyphus** [nk-o/visual-portfolio#88]
I think it would be better to make the default a no-effect hover. It's very easy for those who know css to override it but some will be confused. This would reduce the number of support requests. The current default of subtle zoom could be added back as zoom. It'll also help with some of the rendering issues that transitions might cause. I would also strip font manipulation from the captions and just let them post as figcaption and let themes and themers handle it with optional css in addition, not be default.

**Comment by nk-o** [comment]
If more people will be confused about zoom effect, I will change it definitely. But for now you only one who doesn't like it :)

**Comment by whatsnewsisyphus** [comment]
It's a little strange to not have a plain option. What I would propose is
to have the default be still chosen by default but named zoom (and with a
zoom transition class on the container) , and have a plain option
separately that can be chosen that is the base css without transition
properties. This would make it easier for people to incorporate into themes
without neutralizing css.

**Comment by Lisaa5** [comment]
I'm late to the conversation, but will there be a plain option in the near future update?

I removed the zoom on hover effect by adding this code to the custom CSS, however it stopped working after a recent update.

```
.vp-portfolio__items-style-default .vp-portfolio__item:hover .vp-portfolio__item-img img {
    -webkit-transform: none;
    transform: none;
}
```

**Comment by nk-o** [comment]
No plans to add such option yet.
