### ISSUE TITLE
FireFox rendering images issue - flickering randomly

### ISSUE THREAD

**Issue by nk-o** [nk-o/visual-portfolio#92]
Related topic: https://wordpress.org/support/topic/featured-image-dissapears-almost-random/

**Comment by Vixxd** [comment]
Hi, I am also having this issue with Visual Portofolio added on my homepage within a gutenberg block. It seems to only impact every other portfolio element.

![visualportfolio](https://user-images.githubusercontent.com/5870958/52902164-20524a80-3205-11e9-9f2e-548a98b2f430.gif)

**Comment by whatsnewsisyphus** [comment]
Potential fix below that is not hacky
```
.vp-portfolio__items-style-fade .vp-portfolio__item-img img {
 backface-visibility: hidden
}
```

**Comment by binebabine** [comment]
my problem was: after few seconds the first image disappeared... i dont know why
BUT
this code was the solution:

```
.vp-portfolio__items-style-fade .vp-portfolio__item-img img {
    z-index: 1;
}
.vp-portfolio__items-style-fade .vp-portfolio__item-overlay {
    z-index: 2;
}
```

maybe it will help you?

**Comment by nk-o** [comment]
@binebabine yes, did the trick for Fade effect. Thank you.
